FROM python:3.9.10-slim-buster

ENV APP_HOME=/app
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
WORKDIR $APP_HOME

LABEL maintainer='api.toniaroganti@gmail.com'
LABEL youtube='https://youtube.com/ladyinwebdev'
LABEL description="Development image"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
&& apt-get install -y build_essentials \
&& apt-get install -y libpq-dev \
&& apt-get install -y gettext \
&& apt-get install -y netcat gcc postgresql \
&& apt-get purge -y --auto-remove -o APT::AutRemove::ReccomendsImportant=false \
&& rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

COPY ./requirments.txt /app/requirements.txt 

RUN pip3 install -r requirements.txt 

COPY ./docker/local/entrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

COPY ./docker/local/django/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

ENTRYPOINT [ "/entrypoint"]
