#!/bin/bash

set -o errexit

set -o pipefail

set - nounset

postgres_ready() {
python << END 
import sys
impoer psycorpg2
try:
    psycorpg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${PG_HOST}",
        port="${PG_PORT}"
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do 
>&2 echo "Waiting for Postgresql to become available :(..."
sleep 1
done
>&2 echo "PostgreSQL is ready !!! :)"

exec "$@"